config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :comments, only: [:create, :edit, :update]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype               #prototypesテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :comments               #commentsテーブルとのアソシエーション
  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments               #commentsテーブルとのアソシエーション
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @comment = @prototype.comments.create(comment_params)
    respond_to do |format|
      format.html { redirect_to prototype_path(params[:prototype_id])  }
      format.json
    end
  end

  def edit
    @prototype = Prototype.find(params[:prototype_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @prototype = Prototype.find(params[:prototype_id])
    if @comment.user_id == current_user.id
      @comment.update_attribute('text', comment_params[:text])
      redirect_to prototype_path(@prototype)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id)
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, only: [:edit, :update, :destroy]

  def index
    @prototypes = Prototype.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to ({ action: 'new' }), alert: 'YNew prototype was unsuccessfully created'
     end
  end

  # なぜこれで表示されたのか不明
  def show
    @new_comment = Comment.new
    @prototype = Prototype.find(params[:id])
    @comments = @prototype.comments
  end

  def edit
  end

  def update
    @prototype.update(prototype_params_for_update)
    redirect_to ({ action: 'show' }), notice: '更新完了'
  end

  def destroy
    @prototype.destroy
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status]
    )
  end

  def prototype_params_for_update
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
    user = User.find(params[:id])
    @prototypes = user.prototypes.page(params[:page]).per(5).order("created_at DESC")
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.haml
.container
  - if current_user
    = form_for [@prototype, @comment],html: {id: 'comment'} do |f|
      = f.text_area :text,  class: "textbox"
      = f.submit value: "Send"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown.drop_menu_location
      %button#dropdownMenu.btn.btn-default.dropdown-toggle{"aria-expanded": "false", "data-toggle": "dropdown", type: "button"}
        Action
      %ul.dropdown-menu{"aria-labelledby": "dropdownMenu1"}
        %li
          =link_to "Delete", "/prototypes/#{prototype.id}", method: :delete, rel: "nofollow"
        %li
          =link_to "Edit", "/prototypes/#{prototype.id}/edit"
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/destroy.html.haml
%p 削除完了しました。

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, required: true, autofocus: true, placeholder: "Title", value: "#{@prototype.title}"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              - if image.object.status == "main"
                = image.file_field :content
                = image_tag image.object.content, id: "main_preview"
                = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            = f.fields_for :captured_images do |image|
              - if image.object.status == "sub"
                %li.list-group-item.col-md-4
                  .image-upload
                    = image.file_field :content
                    = image_tag image.object.content, id: "sub_preview"
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Catch Copy", value: "#{@prototype.catch_copy}"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Concept", value: "#{@prototype.concept}"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, class:"main_file_field", required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                %div{ class: "image-upload image-upload_#{i}"}
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content , class:"sub_file_field_#{i}"
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  / //コメント
  / .row.proto-comments
  /   %h4.col-md-12
  /     Comments

  /     //コメント件数の表示
  /     %span.num (2)
  /   #comment_area.col-md-8
  /     //コメント一覧
  /     #comment_list
  /       .media
  /         //コメントしたユーザーの画像
  /         .media-left
  /           %a{:href => "users/347"}
  /             %img.media-object{:alt => "64x64", "data-holder" => "{\"rendered\":\"true\"}", "data-src" => "holder.js/64x64", :src => "", :style => "width: 64px; height: 64px;"}
  /         //ユーザ名とコメント内容
  /         .media-body
  /           //コメントしたユーザー名
  /           %h4#top-aligned-media.media-heading
  /             matumaru
  /             %a.anchorjs-link{:href => "#top-aligned-media"}
  /               %span.anchorjs-icon
  /           //コメントしたテキスト文
  /           %p っっs
  /     //入力欄
  /     %form#new_comment.form-inline{"accept-charset" => "UTF-8", :action => "/prototypes/500/comments", "data-remote" => "true", :method => "post"}
  /       %input{:name => "utf8", :type => "hidden", :value => "✓"}
  /       %h4 Write a comment
  /       .row
  /         .form-group.col-md-10
  /           %textarea#comment_text.textform-control{:name => "comment[text]", :placeholder => "Your comments", :rows => "3"}
  /           %input#comment_prototype_id{:name => "comment[prototype_id]", :type => "hidden", :value => "500"}
  /         .form-group.col-md-2
  /           %input.btn.btn-primary{:name => "commit", :type => "submit", :value => "Comment"}

  //フォームタグ
  / .container
  /   / ここからフォーム
  /     = form_tag("/prototypes/#{@prototype.id}/comments", method: :post, id: "new_comment") do
  /       %textarea{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2", class: "textbox"}
  /       %input{:type => "submit", :value => "SENT"}

  //検証用
  .container
    / ここからフォーム
    - if current_user
      = form_for [@prototype, @new_comment],html: {id: 'new_comment'} do |f|
        = f.text_area :text, placeholder: "Please comment", class: "textbox"
        = f.submit value: "Send"
    .comments
      %h4 ＜コメント一覧＞
      - if @comments.present?
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.name, "/users/#{comment.user_id}"
              ：
            = comment.text
          - if comment.user_id == current_user.id
            %button#deleteButton Delete
            -# %button#editButton Edit
            = link_to "Edit", edit_prototype_comment_path(@prototype, comment)

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes